### ISSUE TITLE
Download retry support

### ISSUE THREAD

**Issue by rphillips** [henrik/sipper#12]
Should definitely try and add retry support for downloads. I get occasional etimeouts going through an entire download.

**Comment by henrik** [comment]
@rphillips That's a good idea – thank you! I haven't seen those errors but maybe it's down to connection speed or something.

Could you paste an example error? I'm asking because you mention "etimeout" and the error I get if I set the HTTP timeout value low is different:

```
> HTTPotion.get("http://example.com/", timeout: 1)
** (HTTPotion.HTTPError) req_timedout
    (httpotion) lib/httpotion.ex:209: HTTPotion.handle_response/1
```

So I want to see if I can reproduce it or at least read up a bit.

**Comment by rphillips** [comment]
sipper looks like a great example. great job, I'll be looking into the code:

```
[GET]    /media/Elixir Sips/041 - File, Part 1/041_File_Part_1.mp4
** (HTTPotion.HTTPError) etimedout
    (httpotion) lib/httpotion.ex:209: HTTPotion.handle_response/1
    (sipper) lib/sipper/dpd_cart_client.ex:17: Sipper.DpdCartClient.get_file/3
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (sipper) lib/sipper/file_downloader.ex:8: Sipper.FileDownloader.run/2
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by henrik** [comment]
Thanks! And thank you for the error output. It's my first Elixir project, so I'm sure there's a lot that could be improved (test coverage if nothing else), but it's been great fun and good learning :) I'll try to look into the etimeouts some day soon.

**Comment by henrik** [comment]
Just an update on this since I'm going through open issues: I think I looked into it back in October and found retries to be a little tricky, so I didn't do it then. I'll leave this ticket open in case anyone else wants to look into it (please feel free) or if I find the time/inclination later.

Or might it be a better idea to make the timeout easily configurable and documenting this clearly? The current timeout for file downloads is 3 hours, which seems generous, but I guess it depends on your connection. And I guess timeouts could happen for other reasons than HTTPotion's time limits.
