### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by sidis405** [henrik/sipper#23]
Hi all. 

I'm trying to build this on mac osx 10.9

I currently have Erlang 19 and Elixir 1.0.5 running but when i finally try to build after pulling the dependencies i'm getting

```
could not compile dependency httpotion, mix compile failed. You can recompile this dependency with `mix deps.compile httpotion` or update it with mix deps.update httpotion
```

Any ideas?

Edit:
I must also add that following the suggestions of that action, still i return to the same issue.
Updating proceeds correctly, but the compile yields the same error as well.

**Comment by henrik** [comment]
Hi! I tried cloning the project fresh on OS X 10.12 with Elixir 1.3.1 and Erlang/OTP 18 and the escript compiles fine.

I'm no expert on Elixir/Mix errors, but maybe it's a compatibility thing with httpotion?

Maybe try changing the dependencies in `mix.exs` to loosen the version requirements of these two libs:

```
      {:ibrowse, "> 0.0.0"},
      {:httpotion, "> 0.0.0"},
```

then try

```
mix deps.update httpotion ibrowse
mix escript.build
```

and see if that works. If it does, it's probably a version compatibility issue, and it could probably be fixed by Sipper using more recent versions of those libs.

**Comment by henrik** [comment]
Closing this. Happy to reopen if someone can add more details.
